"use strict";
const PARAMETERS=new URLSearchParams(location.search);const CONFIG={root:PARAMETERS.get("root")||window.ALMITA_QUICKLOOK_ROOT||"/quicklook",telemetryRoot:PARAMETERS.get("telemetry")||window.ALMITA_TELEMETRY_ROOT||"/telemetry",pollMs:2000,staleMs:30000,telemetryStaleMs:10000};
const $=id=>document.getElementById(id);let lastVersion=null,lastValid=null,pollTimer=null;
const safe=(v,fallback="—")=>v===null||v===undefined||v===""?fallback:v;
const num=(v,d=2)=>typeof v==="number"?v.toLocaleString(undefined,{maximumFractionDigits:d}):safe(v);
const pair=(label,value)=>`<dt>${label}</dt><dd>${safe(value)}</dd>`;
function isStale(updated,now=Date.now()){const t=Date.parse(updated);return !Number.isFinite(t)||now-t>CONFIG.staleMs}
function imageVersion(updated){return encodeURIComponent(updated||"unversioned")}
function summarySpectrum(raw){if(!raw)return null;const q=raw.quicklook_metrics||{};return {gain:raw.gain_db,center:raw.center_frequency_hz,duration:raw.capture_duration_seconds,valid:q.valid_fraction,masked:q.masked_fraction,median:q.median_fractional_excess,sigma:q.robust_sigma_fractional_excess,max:q.max_positive_fractional_excess,min:q.min_fractional_excess,calibration:raw.calibration_level,sampleRate:raw.sample_rate_hz,compatibility:raw.compatibility?.status}}
function summaryWaterfall(raw){if(!raw)return null;const q=raw.quicklook_metrics||{};return {timeBins:raw.time_bins,nativeBins:raw.frequency_bins_native,dashboardBins:raw.frequency_bins_dashboard,duration:raw.capture_duration_seconds,color:raw.color_scale,temporal:q.temporal_rms_of_row_medians,maximum:q.maximum_excursion,maxLabel:q.maximum_excursion_label}}
function summaryMap(raw){if(!raw)return null;return {state:raw.status,points:raw.points?.length,center:raw.map_center,convention:raw.coordinate_convention,coverage:raw.quicklook_metrics?.coverage_fraction,metric:raw.map_metric?.name,environment:raw.environment}}
function telemetryStale(created,now=Date.now()){const t=Date.parse(created);return !Number.isFinite(t)||now-t>CONFIG.telemetryStaleMs}
async function fetchTelemetry(){const response=await fetch(`${CONFIG.telemetryRoot}/telemetry_summary.json`,{cache:"no-store"});if(response.status===404)return null;if(!response.ok)throw new Error(`telemetry: HTTP ${response.status}`);return response.json()}
async function fetchJson(name,optional=false){const response=await fetch(`${CONFIG.root}/${name}`,{cache:"no-store"});if(!response.ok){if(optional&&response.status===404)return null;throw new Error(`${name}: HTTP ${response.status}`)}return response.json()}
function setImage(id,name,version){const img=$(id);img.classList.remove("ready");img.onload=()=>img.classList.add("ready");img.onerror=()=>img.classList.remove("ready");img.src=`${CONFIG.root}/${name}?v=${imageVersion(version)}`}
function progressCard(label,value){return `<div class="stat"><div class="label">${label}</div><div class="value">${safe(value)}</div></div>`}
function render(data){const {status,spectrum,waterfall,map}=data;lastValid=data;$("loading").hidden=true;$("app").hidden=false;
  $("session").textContent=safe(status.session_id);$("status").textContent=safe(status.status);$("status").className=`badge status-${String(status.status||"").toLowerCase()}`;
  $("calibration").textContent=safe(status.calibration_level);$("absolute").textContent=status.absolute_calibration===false?"NO":safe(status.absolute_calibration);$("updated").textContent=safe(status.updated_utc);
  $("environment").hidden=status.environment!=="INDOOR_DEPARTMENT";updateFreshness(status.updated_utc);
  const p=status.session_progress||{};$("progress").innerHTML=[["PLANNED",p.total_planned],["SUCCESS",p.success],["FAILED",p.failed],["DEFERRED",p.deferred],["PENDING",p.pending],["PROCESSED",p.processed],["SKIPPED",status.points_skipped],["BACKLOG",status.backlog_count]].map(x=>progressCard(...x)).join("");
  $("spectrum-point").textContent=`POINT ${safe(status.latest_point_id,"N/A")}`;
  $("spectrum-meta").innerHTML=spectrum?[pair("GAIN",`${num(spectrum.gain)} dB`),pair("CENTER",`${num((spectrum.center||0)/1e6,6)} MHz`),pair("DURATION",`${num(spectrum.duration)} s`),pair("VALID",num(spectrum.valid,4)),pair("MASKED",num(spectrum.masked,4)),pair("COMPATIBILITY",spectrum.compatibility)].join(""):pair("STATUS","NOT AVAILABLE");
  $("fractional-meta").innerHTML=spectrum?[pair("MEDIAN",num(spectrum.median,6)),pair("ROBUST SIGMA",num(spectrum.sigma,6)),pair("MAX VALID",num(spectrum.max,4)),pair("MIN VALID",num(spectrum.min,4))].join(""):pair("STATUS","NOT AVAILABLE");
  $("waterfall-meta").innerHTML=waterfall?[pair("TIME BINS",waterfall.timeBins),pair("NATIVE BINS",waterfall.nativeBins),pair("DASHBOARD BINS",waterfall.dashboardBins),pair("TEMPORAL RMS",num(waterfall.temporal,6)),pair("MAX LABEL",waterfall.maxLabel),pair("MAX EXCURSION",num(waterfall.maximum,4))].join(""):pair("STATUS","NOT AVAILABLE");
  $("map-state").textContent=safe(map?.state,"NOT AVAILABLE");$("map-meta").innerHTML=map?[pair("POINTS",map.points),pair("STATE",map.state),pair("METRIC",map.metric),pair("CONVENTION",map.convention),pair("COVERAGE",num(map.coverage,4)),pair("CENTER RA",num(map.center?.ra_deg,5))].join(""):pair("STATUS","NOT AVAILABLE");
  $("latest-point").innerHTML=[pair("POINT ID",status.latest_point_id),pair("SOURCE","DERIVED PRODUCT"),pair("RA",map?.points?num(data.mapRaw.points.at(-1)?.ra_deg,5):"N/A"),pair("DEC",map?.points?num(data.mapRaw.points.at(-1)?.dec_deg,5):"N/A"),pair("COORD SOURCE",map?.points?safe(data.mapRaw.points.at(-1)?.coordinate_source,"N/A"):"N/A"),pair("PROCESSING",num(status.performance?.point_history?.at(-1)?.total_seconds)+" s")].join("");
  $("instrument").innerHTML=[pair("GAIN",spectrum?`${num(spectrum.gain)} dB`:"N/A"),pair("FREQUENCY",spectrum?`${num(spectrum.center/1e6,6)} MHz`:"N/A"),pair("SAMPLE RATE",spectrum?`${num(spectrum.sampleRate/1e6,3)} MS/s`:"N/A"),pair("BIAS-T","NOT EXPOSED"),pair("PROFILE",status.calibration_profile?.split("/").pop()),pair("CALIBRATION",status.calibration_level)].join("");
  const issues=[...(status.errors||[]).map(x=>({...x,kind:"error"})),...(status.warnings||[]).map(x=>({...x,kind:"warning"}))];$("issues").innerHTML=issues.length?issues.map(x=>`<div class="issue ${x.kind}"><b>${x.kind.toUpperCase()}</b> · ${safe(x.point_id,"SESSION")} · ${safe(x.error||x.warning||x.message)}</div>`).join(""):"<p class=nodata>NO ACTIVE ERRORS</p>";
  const perf=status.performance||{};$("timing").innerHTML=[pair("DISCOVERY",`${num(perf.discovery_seconds,4)} s`),pair("STATE WRITE",`${num(perf.state_write_seconds,4)} s`),pair("PEAK RAM",`${num(perf.peak_rss_mib,1)} MiB`),pair("RATE",`${num(perf.approx_sustainable_points_per_minute,1)} points/min`)].join("");
  const v=status.updated_utc;setImage("spectrum-img","latest_spectrum.png",v);setImage("fractional-img","latest_fractional_excess.png",v);setImage("waterfall-img","latest_waterfall.png",v);setImage("map-img","quicklook_map.png",v)
}
function updateFreshness(updated){const stale=isStale(updated);$("freshness").textContent=stale?"STALE":"LIVE";$("freshness").className=stale?"status-degraded":"status-ok"}
function renderTelemetry(t){if(!t){$("telemetry-status").textContent="NOT AVAILABLE";$("telemetry-freshness").textContent="";for(const id of ["temperature","system","sdr","mount"])$(id).innerHTML='<p class="nodata">TELEMETRY NOT AVAILABLE</p>';return}const stale=telemetryStale(t.created_utc);$("telemetry-status").textContent=safe(t.status);$("telemetry-status").className=`status-${String(t.status||"").toLowerCase()}`;$("telemetry-freshness").textContent=stale?"TELEMETRY STALE":"TELEMETRY LIVE";$("telemetry-freshness").className=stale?"status-degraded":"status-ok";
  $("temperature").innerHTML=[pair("SDR",t.temperatures?.sdr_c==null?safe(t.temperatures?.sdr_status,"NO DATA"):`${num(t.temperatures.sdr_c,2)} °C`),pair("LNA",t.temperatures?.lna_c==null?safe(t.temperatures?.lna_status,"NO DATA"):`${num(t.temperatures.lna_c,2)} °C`)].join("");
  $("system").innerHTML=[pair("CPU",t.system?.cpu_percent==null?"N/A":`${num(t.system.cpu_percent,1)}%`),pair("RAM",t.system?.memory_percent==null?"N/A":`${num(t.system.memory_percent,1)}%`),pair("DISK",t.storage?.percent==null?"N/A":`${num(t.storage.percent,1)}%`),pair("UPTIME",t.uptime_seconds==null?"N/A":`${num(t.uptime_seconds/3600,1)} h`),pair("NETWORK",safe(t.network?.interface)),pair("RX / TX",`${num(t.network?.rx_bytes,0)} / ${num(t.network?.tx_bytes,0)} B`)].join("");
  $("sdr").innerHTML=[pair("RTL_TCP PROCESS",t.sdr?.rtl_tcp_process_detected?"DETECTED":"NOT DETECTED"),pair("PORT 1234",t.sdr?.rtl_tcp_port_listening===true?"LISTENING":t.sdr?.rtl_tcp_port_listening===false?"NOT LISTENING":"UNKNOWN"),pair("EXPECTED FREQ",`${num((t.sdr?.expected_frequency_hz||0)/1e6,6)} MHz`),pair("EXPECTED RATE",`${num((t.sdr?.expected_sample_rate_hz||0)/1e6,3)} MS/s`),pair("EXPECTED GAIN",`${num(t.sdr?.expected_gain_db)} dB`),pair("BIAS-T EXPECTED",t.sdr?.bias_tee_expected?"ON":"UNKNOWN")].join("");
  $("mount").innerHTML=[pair("STATUS",safe(t.mount?.status,"NOT_EXPOSED")),pair("TRACKING",safe(t.mount?.tracking,"N/A")),pair("RA",safe(t.mount?.ra,"N/A")),pair("DEC",safe(t.mount?.dec,"N/A"))].join("")}
async function poll(){try{const [status,telemetry]=await Promise.all([fetchJson("quicklook_live_status.json"),fetchTelemetry().catch(()=>null)]);renderTelemetry(telemetry);$("connection").hidden=true;if(status.updated_utc===lastVersion){updateFreshness(status.updated_utc);return}const [s,w,m]=await Promise.all([fetchJson("latest_spectrum.json",true),fetchJson("latest_waterfall.json",true),fetchJson("quicklook_map.json",true)]);lastVersion=status.updated_utc;render({status,spectrum:summarySpectrum(s),waterfall:summaryWaterfall(w),map:summaryMap(m),mapRaw:m})}catch(error){$("connection").hidden=false;$("connection").textContent=`DATA CONNECTION DEGRADED — ${error.message}`;if(!lastValid){$("loading").textContent="DATA CONNECTION DEGRADED — waiting for derivatives"}}}
function syncJson(name){const request=new XMLHttpRequest();request.open("GET",`${CONFIG.root}/${name}`,false);request.send();return request.status===200?JSON.parse(request.responseText):null}
function start(){if(new URLSearchParams(location.search).get("snapshot")==="1"){const status=syncJson("quicklook_live_status.json"),s=syncJson("latest_spectrum.json"),w=syncJson("latest_waterfall.json"),m=syncJson("quicklook_map.json"),t=(()=>{const r=new XMLHttpRequest();r.open("GET",`${CONFIG.telemetryRoot}/telemetry_summary.json`,false);r.send();return r.status===200?JSON.parse(r.responseText):null})();render({status,spectrum:summarySpectrum(s),waterfall:summaryWaterfall(w),map:summaryMap(m),mapRaw:m});renderTelemetry(t);return}poll();pollTimer=setInterval(poll,CONFIG.pollMs);setInterval(()=>{$("clock").textContent=new Date().toISOString().replace("T"," ").slice(0,19)+"Z";if(lastValid)updateFreshness(lastValid.status.updated_utc)},1000)}
window.AlmitaDashboard={isStale,telemetryStale,imageVersion,summarySpectrum,summaryWaterfall,summaryMap,renderTelemetry,poll,CONFIG};start();
